version: "3.3"
services:
    app:
        build: .
        environment:
            GOOGLE_CLIENT_ID: ""
            GOOGLE_CLIENT_SECRET: ""
            JWT_SECRET: ""
            API_URL: "http://localhost"
            PORT: "3000"
            GOOGLE_API_URL: "https://accounts.google.com/o/oauth2/v2/auth"
        ports: 
            - "3000:3000"
        restart: "always"